import React, { useEffect, useState } from 'react';
import { ShieldCheck, ShieldAlert, AlertTriangle, CheckCircle2 } from 'lucide-react';

/* Pre-Flight panel — renders the deterministic constraint report generated by
   the Python engine. Regenerate with:
   python3 agents/event_ops/schemas/global_ai_berlin.py > public/gaib-preflight.json */

const Card = ({ title, children }) => (
  <div className="panel-glass glass-border rounded-md p-5" style={{ borderColor: 'rgba(255,255,255,0.08)' }}>
    <h2 className="text-sm font-bold mb-4" style={{ fontFamily: 'var(--font-mono)', letterSpacing: '0.08em', color: 'var(--text-2)' }}>{title}</h2>
    {children}
  </div>
);

export default function PreflightPanel() {
  const [report, setReport] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetch('/gaib-preflight.json')
      .then(r => { if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.json(); })
      .then(setReport)
      .catch(e => setError(e.message));
  }, []);

  if (error) {
    return (
      <div className="panel-glass glass-border rounded-md p-8 text-center">
        <p className="text-sm" style={{ color: 'var(--text-2)' }}>No pre-flight report found ({error}).</p>
        <p className="text-xs mt-2" style={{ color: 'var(--text-3)', fontFamily: 'var(--font-mono)' }}>
          Generate one: python3 agents/event_ops/schemas/global_ai_berlin.py &gt; public/gaib-preflight.json
        </p>
      </div>
    );
  }
  if (!report) return <div className="text-sm text-slate-400 p-8">Loading pre-flight report…</div>;

  const d = report.result.validated_data;
  const approved = report.status === 'approved';
  const budget = d.budget || {};
  const categories = budget.categories || {};

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white mb-1">Pre-Flight Check</h1>
          <p className="text-sm text-slate-300">{d.event_name} · {d.date}</p>
        </div>
        <div className="flex items-center gap-2 px-4 py-2 rounded-md font-bold text-sm"
          style={approved
            ? { background: 'rgba(0,229,160,0.12)', color: 'var(--color-green, #34d399)', border: '1px solid rgba(52,211,153,0.35)' }
            : { background: 'rgba(255,107,107,0.12)', color: '#f87171', border: '1px solid rgba(248,113,113,0.35)' }}>
          {approved ? <ShieldCheck size={18} /> : <ShieldAlert size={18} />}
          {approved ? 'APPROVED — all constraints satisfied' : `BLOCKED — ${report.result.reason}`}
        </div>
      </div>

      {/* Violations & risks */}
      {(d.violations.length > 0 || d.risk_flags.length > 0) && (
        <Card title="FINDINGS">
          <div className="space-y-2">
            {d.violations.map((v, i) => (
              <div key={`v${i}`} className="flex items-start gap-2 text-sm text-red-300">
                <ShieldAlert size={15} className="mt-0.5 flex-shrink-0" /> {v}
              </div>
            ))}
            {d.risk_flags.map((r, i) => (
              <div key={`r${i}`} className="flex items-start gap-2 text-sm text-amber-300">
                <AlertTriangle size={15} className="mt-0.5 flex-shrink-0" /> {r}
              </div>
            ))}
          </div>
        </Card>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Budget */}
        <Card title="BUDGET">
          <div className="flex justify-between text-sm mb-1">
            <span style={{ color: 'var(--text-2)' }}>Committed</span>
            <span className="font-semibold text-white">
              €{(budget.committed_total ?? 0).toLocaleString()} / €{(budget.total_ceiling ?? 0).toLocaleString()}
            </span>
          </div>
          <div className="w-full bg-white/5 h-2 rounded overflow-hidden mb-1">
            <div className="h-full" style={{
              width: `${budget.total_ceiling ? Math.min((budget.committed_total / budget.total_ceiling) * 100, 100) : 0}%`,
              background: budget.hard_stop_breached ? '#f87171' : 'linear-gradient(90deg, var(--ef-brand-deep), var(--ef-brand-2))',
            }} />
          </div>
          <div className="text-xs mb-4" style={{ color: 'var(--text-3)' }}>
            Hard stop at €{(budget.hard_stop_at ?? 0).toLocaleString()}
            {budget.hard_stop_breached ? ' — BREACHED' : ''} · headroom €{(budget.headroom ?? 0).toLocaleString()}
          </div>
          <div className="space-y-2">
            {Object.entries(categories).map(([cat, c]) => (
              <div key={cat}>
                <div className="flex justify-between text-xs mb-1">
                  <span style={{ color: 'var(--text-2)' }}>{cat}</span>
                  <span className={c.over ? 'text-red-300 font-semibold' : 'text-slate-300'}>
                    €{c.committed.toLocaleString()} / €{c.ceiling.toLocaleString()}
                  </span>
                </div>
                <div className="w-full bg-white/5 h-1.5 rounded overflow-hidden">
                  <div className="h-full" style={{
                    width: `${c.ceiling ? Math.min((c.committed / c.ceiling) * 100, 100) : 0}%`,
                    background: c.over ? '#f87171' : 'var(--accent-dim, rgba(139,92,246,0.5))',
                  }} />
                </div>
              </div>
            ))}
          </div>
        </Card>

        {/* Staffing */}
        <Card title="STAFFING COVERAGE">
          <div className="space-y-4">
            {Object.entries(d.staffing || {}).map(([role, windows]) => windows.map((w, i) => (
              <div key={`${role}${i}`} className="flex items-start justify-between gap-3">
                <div>
                  <div className="text-sm font-semibold text-white">{role.replace(/_/g, ' ')}</div>
                  <div className="text-xs" style={{ color: 'var(--text-3)' }}>
                    {w.window} · {w.volunteers.join(', ') || 'no one confirmed'}
                    {w.unfilled_placeholder_slots > 0 && ` · ${w.unfilled_placeholder_slots} slot(s) unfilled`}
                  </div>
                </div>
                <span className={`text-xs px-2 py-1 rounded font-semibold flex items-center gap-1 ${w.met ? 'bg-emerald-900/40 text-emerald-300' : 'bg-red-900/40 text-red-300'}`}>
                  {w.met ? <CheckCircle2 size={12} /> : <ShieldAlert size={12} />}
                  {w.confirmed_full_window}/{w.required}
                </span>
              </div>
            )))}
          </div>
        </Card>
      </div>

      {/* AV / equipment */}
      <Card title="AV / EQUIPMENT">
        {Object.keys(d.av_equipment?.missing_dependencies || {}).length === 0 && (d.av_equipment?.double_booked || []).length === 0 ? (
          <div className="flex items-center gap-2 text-sm text-emerald-300">
            <CheckCircle2 size={15} /> Dependency chains closed, no double-booked gear.
          </div>
        ) : (
          <div className="space-y-2 text-sm">
            {Object.entries(d.av_equipment.missing_dependencies).map(([item, deps]) => (
              <div key={item} className="text-red-300 flex items-start gap-2">
                <ShieldAlert size={15} className="mt-0.5 flex-shrink-0" /> {item}: missing {deps.join(', ')}
              </div>
            ))}
            {d.av_equipment.double_booked.map((c, i) => (
              <div key={i} className="text-red-300 flex items-start gap-2">
                <ShieldAlert size={15} className="mt-0.5 flex-shrink-0" />
                {c.item} double-booked ({c.session} {c.window}) — demand {c.concurrent_demand}, available {c.qty_available}
              </div>
            ))}
          </div>
        )}
      </Card>

      {/* Audit line */}
      <div className="text-xs" style={{ color: 'var(--text-3)', fontFamily: 'var(--font-mono)' }}>
        Deterministic constraint engine · schema v{report.version} · input hash {report.result.input_hash?.slice(0, 12)} · same input always produces this exact report
      </div>
    </div>
  );
}
